# # -- 코드를 입력하세요
SELECT SUB.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(SALES * PRICE) AS TOTAL_SALES
FROM BOOK_SALES AS S
JOIN (SELECT A.AUTHOR_ID, B.BOOK_ID, CATEGORY, PRICE, AUTHOR_NAME, PUBLISHED_DATE FROM BOOK AS B JOIN AUTHOR AS A ON B.AUTHOR_ID = A.AUTHOR_ID) AS SUB
ON S.BOOK_ID = SUB.BOOK_ID
WHERE SALES_DATE LIKE '2022-01%'
GROUP BY AUTHOR_NAME, CATEGORY
ORDER BY SUB.AUTHOR_ID, CATEGORY DESC

# SELECT * FROM BOOK_SALES WHERE SALES_DATE LIKE '2022-01%'
# SELECT * FROM BOOK AS B JOIN AUTHOR AS A ON B.AUTHOR_ID = A.AUTHOR_ID
# SELECT A.AUTHOR_ID, B.BOOK_ID, CATEGORY, PRICE FROM BOOK AS B JOIN AUTHOR AS A ON B.AUTHOR_ID = A.AUTHOR_ID