WITH CANT_RENT_CAR AS (
SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE >= '2022-11-01'OR 
        END_DATE BETWEEN '2022-11-01' AND '2022-11-30' OR
        (START_DATE < '2022-11-01' AND END_DATE >= '2022-11-30')
    ), DISCOUNT AS (
    SELECT CAR_TYPE, DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE DURATION_TYPE LIKE '30일%')

SELECT C.CAR_ID, C.CAR_TYPE, ROUND(((C.DAILY_FEE * 30) * (100 - D.DISCOUNT_RATE) / 100), 0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS C
JOIN DISCOUNT AS D
ON C.CAR_TYPE = D.CAR_TYPE
WHERE C.CAR_ID NOT IN (SELECT * FROM CANT_RENT_CAR) AND (C.CAR_TYPE = '세단' OR C.CAR_TYPE = 'SUV')
HAVING FEE BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, C.CAR_TYPE, C.CAR_ID;

# SELECT COUNT(*) FROM CANT_RENT_CAR
# SELECT * FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
#     WHERE START_DATE >= '2022-11-01'OR 
#         END_DATE BETWEEN '2022-11-01' AND '2022-11-30' OR
#         (START_DATE < '2022-11-01' AND END_DATE >= '2022-11-30')