SELECT USER_ID, NICKNAME, CONCAT(U.CITY, " ", U.STREET_ADDRESS1, " ", U.STREET_ADDRESS2) AS '전체주소', 
    CONCAT(SUBSTRING(TLNO, 1, 3), "-", SUBSTRING(TLNO,4,4), "-", SUBSTRING(TLNO, 8, 11)) AS TLNO
FROM USED_GOODS_BOARD AS B
JOIN USED_GOODS_USER AS U
ON B.WRITER_ID = U.USER_ID
GROUP BY B.WRITER_ID
HAVING COUNT(WRITER_ID) >= 3
ORDER BY USER_ID DESC;