-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) AS YEAR,
        MONTH(SALES_DATE) AS MONTH,
        COUNT(DISTINCT(O.USER_ID)) AS PURCHASED_USERS,
        ROUND(COUNT(DISTINCT(O.USER_ID)) / (SELECT COUNT(*) FROM USER_INFO WHERE JOINED LIKE '2021%'), 1) AS PUCHASED_RATIO
FROM ONLINE_SALE AS O
JOIN USER_INFO AS U
ON O.USER_ID = U.USER_ID
WHERE U.JOINED LIKE '2021%'
GROUP BY 1,2
ORDER BY 1,2