-- 코드를 입력하세요
SELECT H.HISTORY_ID, IF(DURATION_TYPE IS NULL , ROUND(DAILY_FEE*(DATEDIFF(END_DATE, START_DATE) + 1),0),ROUND((DATEDIFF(END_DATE, START_DATE) + 1)*DAILY_FEE*(100 - DISCOUNT_RATE) / 100, 0)) AS FEE 
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
JOIN CAR_RENTAL_COMPANY_CAR AS C
ON H.CAR_ID = C.CAR_ID

LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P
ON (CASE 
    WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상'
    WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN '30일 이상'
    WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN '7일 이상'
    ELSE NULL
    END) = P.DURATION_TYPE AND P.CAR_TYPE = '트럭'
WHERE C.CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC