WITH RECURSIVE CTE AS (
    SELECT 0 AS NUM
    UNION ALL
    SELECT NUM+1 FROM CTE
    WHERE NUM < 23)

SELECT NUM AS HOUR, COUNT(ANIMAL_ID) AS COUNT
FROM CTE AS C
LEFT JOIN ANIMAL_OUTS AS O
ON C.NUM = HOUR(O.DATETIME)
GROUP BY HOUR