-- 코드를 작성해주세요
SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, 
        (B.SIZE - SIZE_OF_COLONY) AS YEAR_DEV,
        ID
        
FROM ECOLI_DATA AS A

JOIN (SELECT MAX(SIZE_OF_COLONY) AS SIZE, YEAR(DIFFERENTIATION_DATE) AS DATE 
        FROM ECOLI_DATA
        GROUP BY DATE) B
ON YEAR(DIFFERENTIATION_DATE) = B.DATE
ORDER BY YEAR(DIFFERENTIATION_DATE), YEAR_DEV