-- 코드를 작성해주세요
SELECT ID, FISH_NAME, I.LENGTH
FROM FISH_INFO AS I
JOIN (SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH FROM FISH_INFO GROUP BY FISH_TYPE) AS M
ON M.FISH_TYPE = I.FISH_TYPE AND I.LENGTH = M.LENGTH
JOIN FISH_NAME_INFO AS N
ON I.FISH_TYPE = N.FISH_TYPE
ORDER BY ID
    
