SELECT ID, N.FISH_NAME, I.LENGTH
FROM FISH_INFO AS I
JOIN (SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
        FROM FISH_INFO
        GROUP BY FISH_TYPE) AS SUB
ON I.FISH_TYPE = SUB.FISH_TYPE AND I.LENGTH = SUB.LENGTH
JOIN FISH_NAME_INFO AS N
ON I.FISH_TYPE = N.FISH_TYPE
ORDER BY ID;


