-- 코드를 입력하세요
SELECT CONCAT('/home/grep/src/', S.BOARD_ID,'/', FILE_ID, FILE_NAME, FILE_EXT)
FROM (SELECT BOARD_ID FROM USED_GOODS_BOARD ORDER BY VIEWS DESC LIMIT 1) AS S
JOIN USED_GOODS_FILE AS F
ON S.BOARD_ID = F.BOARD_ID
ORDER BY FILE_ID DESC
