WITH FECODE AS (
    SELECT SUM(CODE) AS CODE FROM SKILLCODES WHERE CATEGORY = 'Front End'),
    PYCODE AS (
    SELECT CODE AS CODE FROM SKILLCODES WHERE NAME = 'Python'),  
    C_CODE AS (
    SELECT CODE AS CODE FROM SKILLCODES WHERE NAME = 'C#')


SELECT (CASE 
        WHEN D.SKILL_CODE & FECODE.CODE AND D.SKILL_CODE & PYCODE.CODE THEN 'A'
        WHEN D.SKILL_CODE & C_CODE.CODE THEN 'B'
        WHEN D.SKILL_CODE & FECODE.CODE THEN 'C' END) AS GRADE,
        ID, EMAIL

FROM DEVELOPERS D, FECODE, PYCODE, C_CODE
HAVING GRADE IS NOT NULL
ORDER BY GRADE, ID;